global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_config_files:
  - scrape.d/*.yml

scrape_configs:
  - job_name: llmops-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend:8000
